---
language: node_js
node_js:
  - "9"
sudo: true
dist: trusty

cache:
  directories:
    - node_modules

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env:
        - DISPLAY=:99.0
        - CC=clang
        - CXX=clang++
        - npm_config_clang=1
        - TARGET_ARCH=x64
        - OS=LINUX
    - os: osx
      osx_image: xcode7.3
      env:
        - TARGET_ARCH=x64
        - OS=DARWIN
        - DISPLAY=:99.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb

before_install:
  - node --version && npm --version
  - "npm config set spin false"
  - "npm install -g node-gyp"

install:
  - npm install
  - Xvfb :99 -screen 0 1024x768x24 +extension RANDR & > /dev/null 2>&1 &

script:
  - npm test

after_success:
  # Todo: Fix this
  # Report code coverage
  # - node ./node_modules/.bin/codecov
